theme: charlolamode
title: zoltanh.ca

params:
    author: Zoltan Hegyi


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Zoltan Hegyi
        description: |
          Hello, I am Zoltan, a mechanical engineering student at Concordia.

    mainSections: []

    socialIcons: []
#        - name: buymeacoffee
#          url: "https://ko-fi.com/heycharlola"
#        - name: github
#          url: "https://github.com/charlola"
#        - name: linkedin
#          url: "https://www.linkedin.com/in/heycharlola/"

    assets:
          favicon: "/static/images/favicon.png"
          favicon16x16: "/static/images/favicon-16x16.png"
          favicon32x32: "/static/images/favicon-32x32.png"
menu:
    main:
        - name: Nothing
          url: nothing/
          weight: 30
